apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:      
    - port: 80 
      targetPort: 80
      nodePort: 31000
      protocol: TCP
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)

# you have to enable ingress in minikube : minikube addons enable ingress