apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beater
  labels:
    app: celery-beater
spec:
  replicas: 1
  selector:
    matchLabels:
      name: celery-beater
  template:
    metadata:
      labels:
        name: celery-beater
        tier: backend
    spec:
      containers:
        - name: celery-beater
          image: django_app:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "celery -A core beat -l info"]
          envFrom:
            - configMapRef:
                name: django-config
          resources:
            limits:
              memory: 100Mi
              cpu: "100m"
            requests:
              memory: 100Mi
              cpu: "100m"

          volumeMounts:
            - name: media-volume-mount
              mountPath: /usr/src/app/media

      volumes:
        - name: media-volume-mount
          persistentVolumeClaim:
            claimName: media-pvc
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /core/media

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: media-pv
