apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    name: postgres
  type: LoadBalancer
  ports:
  - name: main
    port: 5432
    targetPort: 5432