apiVersion: v1
kind: Service
metadata:
  name: django-svc
  labels:
    app: django-svc
spec:
  selector:
    name: django
  type: ClusterIP
  ports:
  - name: main
    port: 8000
    targetPort: 8000